# NOTE: update this with your service name
service: post-by-backend

# Create an optimized package for our functions 
package:
  individually: true

plugins:
  - serverless-bundle # Package our functions with Webpack
  - serverless-offline
  - serverless-dotenv-plugin # Load .env as environment variables

provider:
  name: aws
  runtime: nodejs12.x
  stage: dev
  region: sa-east-1
  environment:
    itemTableName: Item
    reserveTableName: Reserve
  iamRoleStatements:
    - Effect: Allow
      Action:
        - dynamodb:Scan
        - dynamodb:Query
        - dynamodb:GetItem
        - dynamodb:PutItem
        - dynamodb:UpdateItem
        - dynamodb:DeleteItem
        - dynamodb:DescribeTable
      Resource: "arn:aws:dynamodb:sa-east-1:*:*"

functions:
  - ${file(sls/functions/item/get-item.yml)}
  - ${file(sls/functions/item/list-item.yml)}
  - ${file(sls/functions/email/send-email.yml)}
  - ${file(sls/functions/reserve/create-reserve.yml)}
  - ${file(sls/functions/reserve/list-reserve.yml)}
  - ${file(sls/functions/reserve/delete-reserve.yml)}

resources:
  - ${file(sls/resources/api-gateway-errors.yml)}